version: "3"

services:
  web:
    build: .
    entrypoint: ["./wait-for-it.sh", "db:5432", "--"]
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: kartoza/postgis:14-3.2
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  pgdata:
