# Generated by Django 3.2.12 on 2022-02-18 21:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True)),
                ('postal_code', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('federal_district', models.CharField(max_length=255)),
                ('region_type', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('area_type', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('city_type', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('settlement_type', models.CharField(max_length=255)),
                ('settlement', models.CharField(max_length=255)),
                ('kladr_id', models.CharField(max_length=255)),
                ('fias_id', models.CharField(max_length=255)),
                ('fias_level', models.CharField(max_length=255)),
                ('capital_marker', models.CharField(max_length=255)),
                ('okato', models.CharField(max_length=255)),
                ('oktmo', models.CharField(max_length=255)),
                ('tax_office', models.CharField(max_length=255)),
                ('timezone', models.CharField(max_length=255)),
                ('population', models.CharField(max_length=255)),
                ('foundation_year', models.CharField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, unique=True)),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
            },
        ),
    ]
